services:
  orbbec_ros2:
    build:
      context: .
      dockerfile: .ci/Dockerfile
      target: dev
    container_name: orbbec_dev
    privileged: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/host_ws
      - /dev:/dev
    stdin_open: true
    tty: true