services:
  orbbec_ros2:
    build:
      context: .
      dockerfile: .ci/Dockerfile
      target: dep
    container_name: orbbec_deploy
    user: root  # Ensure root for hardware access in deployment
    privileged: true
    network_mode: host
    ipc: host
    pid: host
    restart: always
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - /run/udev:/run/udev
    devices:
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
      - /dev/input:/dev/input
      - /dev/bus/usb:/dev/bus/usb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]